import { Recipe } from '../types/types.ts';

export const recipes: Recipe[] = [
  {
    id: '1',
    name: 'Завтрак',
    image: '',
    ingredients: ['сосиска', 'картошка'],
    steps: ['Порезать', 'Подождать 5 минут'],
    videoLink: '',
    showUsername: true,
    ownerUsername: 'ramazan',
  },
  {
    id: '1',
    name: 'Завтрак',
    image: '',
    ingredients: ['сосиска', 'картошка'],
    steps: ['Порезать', 'Подождать 5 минут'],
    videoLink: '',
    showUsername: true,
    ownerUsername: 'ramazan',
  },
  {
    id: '1',
    name: 'Завтрак',
    image: '',
    ingredients: ['сосиска', 'картошка'],
    steps: ['Порезать', 'Подождать 5 минут'],
    videoLink: '',
    showUsername: true,
    ownerUsername: 'ramazan',
  },
  {
    id: '1',
    name: 'Завтрак',
    image: '',
    ingredients: ['сосиска', 'картошка'],
    steps: ['Порезать', 'Подождать 5 минут'],
    videoLink: '',
    showUsername: true,
    ownerUsername: 'ramazan',
  },
  {
    id: '1',
    name: 'Завтрак',
    image: '',
    ingredients: ['сосиска', 'картошка'],
    steps: ['Порезать', 'Подождать 5 минут'],
    videoLink: '',
    showUsername: true,
    ownerUsername: 'ramazan',
  },
  {
    id: '1',
    name: 'Завтрак',
    image: '',
    ingredients: ['сосиска', 'картошка'],
    steps: ['Порезать', 'Подождать 5 минут'],
    videoLink: '',
    showUsername: true,
    ownerUsername: 'ramazan',
  },
  {
    id: '1',
    name: 'Завтрак',
    image: '',
    ingredients: ['сосиска', 'картошка'],
    steps: ['Порезать', 'Подождать 5 минут'],
    videoLink: '',
    showUsername: true,
    ownerUsername: 'ramazan',
  },
  {
    id: '1',
    name: 'Завтрак',
    image: '',
    ingredients: ['сосиска', 'картошка'],
    steps: ['Порезать', 'Подождать 5 минут'],
    videoLink: '',
    showUsername: true,
    ownerUsername: 'ramazan',
  },
  {
    id: '1',
    name: 'Завтрак',
    image: '',
    ingredients: ['сосиска', 'картошка'],
    steps: ['Порезать', 'Подождать 5 минут'],
    videoLink: '',
    showUsername: true,
    ownerUsername: 'ramazan',
  },
];
